### PR TITLE
Update sensor_pull.c

### PR DESCRIPTION
**Pull request by rickiewars**
Any reason why the file system was not initialized?

### CODE REVIEW

**Comment by LOorts-Aloxy** [comment]
Hi Ricklewars,

Thank you for your merge request. The filesystem already gets initialized inside alp_layer_init in alp_layer.c. I see that we do this in sensor_push.c but I think the cleanest solution would be to first initialize alp_layer and only then d7ap.

**Comment by rickiewars** [comment]
> 
> 
> Hi Ricklewars,
> 
> Thank you for your merge request. The filesystem already gets initialized inside alp_layer_init in alp_layer.c. I see that we do this in sensor_push.c but I think the cleanest solution would be to first initialize alp_layer and only then d7ap.

I've updated the pull request. Is this what you meant @LOorts-Aloxy ?

**Comment by LOorts-Aloxy** [comment]
This is exactly what I meant, thank you for the merge request!

**Comment by rickiewars** [comment]
No problem, great to be at service ;)

**Pull request merged**
